### ISSUE TITLE
Add conda-store UI to demo.nebari.dev

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari-demo#19]
From Pierre:
[conda-store readme](https://github.com/Quansight/conda-store-ui/blob/main/README.md)

**Comment by iameskild** [comment]
We need the `conda-store-ui` image available on a registry, opened this PR to build/push these images to ghcr:
https://github.com/Quansight/conda-store-ui/pull/138

**Comment by iameskild** [comment]
I tried deployed the `conda-store-ui` as a simple kubernetes pod, using the image that was built in the PR linked above:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: qhub-conda-store-ui
  namespace: dev
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - general
  containers:
  - name: conda-store-ui
    image: ghcr.io/iameskild/conda-store-ui:sha-76eb6b0
```
> note: I added the required env vars to the `.env` before building this image.

The conda-store-ui pod seems to start and run without any issues however when I navigate to the `/conda-store` endpoint, I still get the old conda-store UI. 

I have tried comparing the demo.nebari.dev `conda-store-config.py` with the `conda-store-config.py` used as an example in the conda-store-ui repo ([here](https://github.com/Quansight/conda-store-ui/blob/main/docker/assets/conda_store_config.py)) to see if there updates there that are needed but nothing jumps out at me.

**Comment by dharhas** [comment]
The old and new UI's will run in parallel. The ld UI still has some things that the new ui doesn't have (i.e. edit namespaces etc). You probably need to make sure the old and new ui are running on different endpoints. From what I can tell the config file runs the conda-store server on port 5000 and the ui on port 9000. Also I think (check with @pierrotsmnrd), that the config spins up conda-store and conda-store-ui but in your case there are seperate deployment scripts fo conda-store already in Nebari so you should only need to spin up conda-store-ui and point it to the existing server.

**Comment by iameskild** [comment]
update: 
A `conda-store-ui` deployment (+service +ingressroute) have been created as outlined below but the old UI is still present. 

I can confirm:
- the `conda-store-ui` seems to be running and there are no errors in the logs, it just appears "hidden"
- the `conda-store-server` is using port 5000 while the `conda-store-ui` is using port 80
  - the still share the same endpoint `/conda-store`
  - I have tried creating two separate endpoints but that fails with `Cannot GET /conda-store` or `Cannot GET /conda-store-ui`
- the `.env` is setup correctly

---

Currently deployed on `demo.nebari.dev`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qhub-conda-store-ui
  namespace: dev
  labels:
    role: qhub-conda-store-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      role: qhub-conda-store-ui
  template:
    metadata:
      labels:
        role: qhub-conda-store-ui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - general
      containers:
      - name: conda-store-ui
        image: ghcr.io/iameskild/conda-store-ui:sha-4f81bf6
        env:
#         - name: NODE_ENV
#           value: "production"

--- 
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: conda-store-ui
  namespace: dev
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`demo.nebari.dev`) && PathPrefix(`/conda-store`)
    services:
    - name: qhub-conda-store-ui
      port: 80
    priority: 1    # an attempt to prioritize this route over conda-store-server

---
apiVersion: v1
kind: Service
metadata:
  name: qhub-conda-store-ui
  namespace: dev
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: conda-store-ui
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    role: qhub-conda-store-ui
  sessionAffinity: None
  type: ClusterIP
```
